### ISSUE TITLE
Question Regarding GPU-requirement

### ISSUE THREAD

**Issue by SimonWesterlind** [sheng-z/stog#10]
Hi!

With your statement in the **README**, *"Make sure that you have at least two GeForce GTX TITAN X GPUs to train the full model."*, do you mean that you require this setup specifically, or do you just require GPU-memory equivalent to, or greater than, two GeForce GTX TITAN X GPUs? Or is there some other interpretation/requirement completely?

Thanks in advance,
Simon

**Comment by sheng-z** [comment]
Hi,

It is just a requirement for GPU memory. As long as you have enough memory, it will be fine.

Best,
Sheng

**Comment by SimonWesterlind** [comment]
Ok, good! Thank you! :)
