### ISSUE TITLE
evaluation.sh requires python2

### ISSUE THREAD

**Issue by TonalidadeHidrica** [sheng-z/stog#4]
I tried to run the evaluation script (`tools/amr-evaluation-tool-enhanced/evaluation.sh`), but when it was run in a environment without Python 2 (or, there doesn't exist an executable `python2` in PATH), it results in a error like "python2: command not found".  This message was also shown during the training.  Could you write that the evaluation needs Python 2 in the README.md?

**Comment by sheng-z** [comment]
Thanks!
A note has been added to README.
